name: Benchmark Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    paths:
    - 'packages/**'
    - '.github/**'
  issue_comment:
    types: [created]

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: khan/pull-request-comment-trigger@master
      id: check
      with:
        trigger: 'graphyne bench'
        reaction: '+1'
        prefix_only: true
      env:
        GITHUB_TOKEN: ${{github.token}}
    - uses: actions/checkout@v2
    - uses: ./.github/actions/graphql-bench-pr
      if: ${{ github.event_name == 'pull_request' || steps.check.outputs.triggered == 'true' }}
      with:
        repoToken: ${{github.token}}
        