name: Benchmark Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    paths:
    - 'packages/**'
    - '.github/**'
  issue_comment:
    types: [created]

jobs:
  bench:
    if: github.event.pull_request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/graphql-bench-pr
      with:
        repoToken: ${{github.token}}
  bench-manual:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '@graphyne bench'
          reaction: '+1'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/checkout@v2
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'
        