name: On PR comments
on:
  issue_comment:
    types: [created]
jobs:
  bench:
    name: Benchmark
    runs-on: ubuntu-latest
    if: github.event_name.payload.issue.pull_request
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - uses: ./.github/actions/bench-compare
        if: github.payload.comment.body == '@graphyne bench compare-all'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

